global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'transformer'
    static_configs:
      - targets: ['transformer:8000']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'streamsets'
    static_configs:
      - targets: ['streamsets:18630']
    metrics_path: /rest/v1/metrics/prometheus
    scrape_interval: 30s
